# Registration Page Locators
linkText_Register = "REGISTER"
text_FirstName = "name:firstName"
text_LastName = "name:lastName"
text_Phone = "name:phone"
text_Email = "name:userName"
text_Address = "name:address1"
text_City = "name:city"
text_State = "name:state"
text_PostalCode = "name:postalCode"
dropdown_Country = "name:country"
text_RegisterUserName = "name:email"
text_RegisterPassword = "name:password"
text_RegisterConfirmPassword = "name:confirmPassword"
button_RegisterSubmit = "name:submit"
